server:
  port: 8081
  servlet:
    context-path: /us   #上下文的路径
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_sb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.zc.pojo       #扫描实体类包
  configuration:
    map-underscore-to-camel-case: true    #驼峰转换