server:
  port: 10086
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
#  instance:
#    prefer-ip-address: true   #可以将IP注册到Eureka Server上,如果不配置就是机器的主机名
#    ip-address: 127.0.0.1
spring:
  application:
    name: eureka-server       #服务名称，不写否则就是 UNKNOWN
